global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]

  - job_name: tether-probe-staging
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - {{STAGING_BASE_URL}}/readyz
          - {{STAGING_BASE_URL}}/healthz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        target_label: instance
      - target_label: environment
        replacement: staging

  - job_name: tether-probe-production
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - {{PRODUCTION_BASE_URL}}/readyz
          - {{PRODUCTION_BASE_URL}}/healthz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        target_label: instance
      - target_label: environment
        replacement: production
